import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Boxes, CheckCircle2, Clock3, Layers3, Music2 } from "lucide-react";
import { BRCompanion } from "@/components/central/BRCompanion";

export const metadata: Metadata = { title: "BR Solutions | BR STUDIOS Central", description: "Sistemas de BR que alcanzaron suficiente claridad y utilidad para resolver problemas de forma repetible." };

const solutions = [
  { id: "aluxor", name: "BRTuNegocio / ALUXOR", maturity: "Candidato fuerte", project: "BRTuNegocio / ALUXOR", projectHref: "/central/projects#aluxor", problem: "Negocios que operan compras, recepción, inventario y proyectos con información fragmentada.", repeatable: "La arquitectura modular permite reutilizar flujos operativos sin convertir cada implementación en un sistema completamente distinto.", missing: "Definir con claridad qué parte del producto es estándar, qué se configura por negocio y cómo será el onboarding fuera del entorno actual.", ready: false, icon: Layers3 },
  { id: "br-platform", name: "BR Platform", maturity: "Producto activo", project: "BR Platform", projectHref: "/central/projects#br-platform", problem: "Artistas y catálogos musicales que necesitan reunir beats, acceso, licencias y experiencia digital.", repeatable: "Ya existe como producto desplegado y sus flujos principales pueden servir a más de un artista o catálogo.", missing: "Seguir endureciendo licencias, accesos y procesos comerciales antes de tratar cada capacidad como solución independiente.", ready: true, icon: Music2 },
];

export default function SolutionsPage() {
  return <main className="min-h-screen bg-[#09090b] text-[#f3eee6]">
    <div className="pointer-events-none fixed inset-x-0 top-0 h-[760px] bg-[radial-gradient(circle_at_18%_10%,rgba(59,130,246,0.12),transparent_30%),radial-gradient(circle_at_82%_10%,rgba(168,85,247,0.12),transparent_30%)]" />
    <header className="relative z-10 border-b border-white/[0.06] bg-[#09090b]/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/central" className="inline-flex items-center gap-2 text-sm font-black text-zinc-300 transition hover:text-white"><ArrowLeft className="h-4 w-4" /> BR Central</Link><span className="text-[10px] font-black uppercase tracking-[0.34em] text-violet-300">BR Solutions</span></div></header>
    <section className="relative z-10 mx-auto grid max-w-7xl gap-10 px-5 pb-16 pt-16 sm:px-8 sm:pt-24 lg:grid-cols-[1.2fr_.72fr] lg:items-start"><div><p className="text-[11px] font-black uppercase tracking-[0.32em] text-violet-300">Cuando construir deja de ser suficiente //</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[0.94] tracking-[-0.06em] sm:text-7xl">Una Solution debe poder resolver algo <span className="text-zinc-500">otra vez.</span></h1><p className="mt-7 max-w-3xl text-base leading-8 text-zinc-400 sm:text-lg">No todo Project llega aquí. Solutions registra sistemas cuya utilidad empieza a ser repetible fuera del caso que los originó, y también deja visible lo que todavía falta antes de llamarlos solución madura.</p></div><BRCompanion /></section>
    <section className="relative z-10 mx-auto max-w-7xl px-5 pb-20 sm:px-8"><div className="mb-6 border-t border-white/[0.07] pt-7"><p className="text-[10px] font-black uppercase tracking-[0.3em] text-zinc-600">Evaluación de madurez //</p><p className="mt-2 text-sm text-zinc-500">Problema claro → utilidad repetible → límites conocidos → solución.</p></div><div className="grid gap-4">{solutions.map(({ id,name,maturity,project,projectHref,problem,repeatable,missing,ready,icon:Icon }) => <article id={id} key={name} className="scroll-mt-32 rounded-[30px] border border-white/[0.075] bg-white/[0.025] p-6 sm:p-8"><div className="grid gap-8 lg:grid-cols-[.68fr_1.32fr]"><div><span className="grid h-11 w-11 place-items-center rounded-2xl border border-violet-300/15 bg-violet-400/[0.05] text-violet-200"><Icon className="h-5 w-5" /></span><h2 className="mt-6 text-3xl font-black tracking-[-0.04em]">{name}</h2><span className="mt-3 inline-flex items-center gap-2 rounded-full border border-violet-300/15 px-3 py-1.5 text-xs font-black text-violet-200">{ready ? <CheckCircle2 className="h-3.5 w-3.5" /> : <Clock3 className="h-3.5 w-3.5" />}{maturity}</span><Link href={projectHref} className="mt-5 flex items-center gap-2 text-xs font-black text-blue-300 transition hover:text-white">Viene de Project: {project} <ArrowRight className="h-3.5 w-3.5" /></Link></div><div className="grid gap-3 sm:grid-cols-3"><SolutionCell label="Problema repetible" text={problem} /><SolutionCell label="Qué ya se repite" text={repeatable} /><SolutionCell label={ready ? "Siguiente madurez" : "Qué falta"} text={missing} /></div></div></article>)}</div></section>
    <section className="relative z-10 mx-auto max-w-7xl px-5 pb-24 sm:px-8"><div className="rounded-[32px] border border-violet-300/15 bg-gradient-to-br from-blue-500/[0.05] to-violet-500/[0.09] p-8 sm:p-10"><div className="flex items-center gap-3 text-violet-200"><Boxes className="h-5 w-5" /><span className="text-[10px] font-black uppercase tracking-[0.3em]">Regla de Solutions</span></div><h2 className="mt-5 max-w-4xl text-4xl font-black tracking-[-0.05em] sm:text-5xl">No promovemos una función. Promovemos una capacidad comprobable.</h2><p className="mt-5 max-w-3xl leading-7 text-zinc-400">Llegar a Solutions no significa que el trabajo terminó. Significa que ya podemos explicar qué problema resuelve, qué parte es repetible y cuáles son sus límites.</p><Link href="/catalogo" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#f3eee6] px-5 py-3 text-sm font-black text-[#09090b]">Ver catálogo público <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main>;
}

function SolutionCell({ label, text }: { label: string; text: string }) { return <div className="rounded-[22px] border border-white/[0.07] bg-black/15 p-5"><p className="text-[10px] font-black uppercase tracking-[0.24em] text-zinc-600">{label}</p><p className="mt-3 text-sm leading-6 text-zinc-400">{text}</p></div>; }
