import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, FlaskConical, Layers3, Network } from "lucide-react";
import { BRCompanion } from "@/components/central/BRCompanion";
import { EcosystemConnections } from "@/components/central/EcosystemConnections";
import { ecosystemSharedPrinciples } from "@/lib/central/ecosystem";

export const metadata: Metadata = { title: "BR Ecosystem | BR STUDIOS Central", description: "Mapa de relaciones entre experimentos, proyectos, soluciones e infraestructura de BR STUDIOS." };

export default function EcosystemPage() {
  return <main className="min-h-screen bg-[#09090b] text-[#f3eee6]">
    <div className="pointer-events-none fixed inset-x-0 top-0 h-[820px] bg-[radial-gradient(circle_at_18%_10%,rgba(34,211,238,0.10),transparent_30%),radial-gradient(circle_at_82%_12%,rgba(139,92,246,0.13),transparent_30%)]" />
    <header className="relative z-10 border-b border-white/[0.06] bg-[#09090b]/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/central" className="inline-flex items-center gap-2 text-sm font-black text-zinc-300 transition hover:text-white"><ArrowLeft className="h-4 w-4" /> BR Central</Link><span className="text-[10px] font-black uppercase tracking-[0.34em] text-cyan-300">BR Ecosystem</span></div></header>
    <section className="relative z-10 mx-auto grid max-w-7xl gap-10 px-5 pb-16 pt-16 sm:px-8 sm:pt-24 lg:grid-cols-[1.2fr_.72fr] lg:items-start"><div><p className="text-[11px] font-black uppercase tracking-[0.32em] text-cyan-300">Nada vive completamente aislado //</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[0.94] tracking-[-0.06em] sm:text-7xl">Ecosystem muestra <span className="text-zinc-500">lo que viaja entre proyectos.</span></h1><p className="mt-7 max-w-3xl text-base leading-8 text-zinc-400 sm:text-lg">No es otro catálogo. Aquí se conserva qué experimento alimentó un proyecto, qué proyecto maduró hacia una solución y qué aprendizajes técnicos empiezan a repetirse en distintas partes de BR.</p></div><BRCompanion /></section>
    <section className="relative z-10 mx-auto max-w-7xl px-5 pb-20 sm:px-8"><div className="mb-6 border-t border-white/[0.07] pt-7"><p className="text-[10px] font-black uppercase tracking-[0.3em] text-zinc-600">Relaciones visibles //</p><p className="mt-2 text-sm text-zinc-500">No solo qué existe, sino qué produjo qué.</p></div><EcosystemConnections /></section>
    <section className="relative z-10 mx-auto max-w-7xl px-5 pb-20 sm:px-8"><div className="mb-6 border-t border-white/[0.07] pt-7"><p className="text-[10px] font-black uppercase tracking-[0.3em] text-zinc-600">Aprendizajes compartidos //</p><p className="mt-2 text-sm text-zinc-500">Cuando una idea aparece en más de un sistema, empieza a convertirse en criterio BR.</p></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{ecosystemSharedPrinciples.map(({title,text}) => <article key={title} className="rounded-[25px] border border-white/[0.07] bg-black/15 p-6"><Network className="h-5 w-5 text-violet-300" /><h2 className="mt-6 text-xl font-black tracking-[-0.03em]">{title}</h2><p className="mt-3 text-sm leading-6 text-zinc-500">{text}</p></article>)}</div></section>
    <section className="relative z-10 mx-auto max-w-7xl px-5 pb-24 sm:px-8"><div className="rounded-[32px] border border-cyan-300/15 bg-gradient-to-br from-cyan-500/[0.05] to-violet-500/[0.09] p-8 sm:p-10"><div className="flex items-center gap-3 text-cyan-200"><Network className="h-5 w-5" /><span className="text-[10px] font-black uppercase tracking-[0.3em]">Mapa vivo</span></div><h2 className="mt-5 max-w-4xl text-4xl font-black tracking-[-0.05em] sm:text-5xl">Central ya puede contar una historia completa sin fingir que todo está terminado.</h2><p className="mt-5 max-w-3xl leading-7 text-zinc-400">Lab conserva incertidumbre. Projects conserva construcción. Solutions conserva madurez. Ecosystem conserva las relaciones. Cuando una pieza cambie, el mapa debe poder cambiar con ella.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/central/lab" className="inline-flex items-center gap-2 rounded-full bg-[#f3eee6] px-5 py-3 text-sm font-black text-[#09090b]"><FlaskConical className="h-4 w-4" /> Empezar en Lab</Link><Link href="/central/projects" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-5 py-3 text-sm font-black text-zinc-300"><Layers3 className="h-4 w-4" /> Ver Projects</Link></div></div></section>
  </main>;
}
