import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, FlaskConical, RadioTower, ShieldCheck, Sparkles } from "lucide-react";
import { BRCompanion } from "@/components/central/BRCompanion";

export const metadata: Metadata = { title: "BR Lab | BR STUDIOS Central", description: "Experimentos, hipótesis y aprendizajes técnicos de BR STUDIOS antes de convertirse en proyectos." };

const experiments = [
  { name: "Radar de red contextual", status: "Avanzó a Project", hypothesis: "La identidad y el historial pueden explicar una red mejor que una lista cambiante de IPs.", evidence: "Las pruebas de WiFi Monitor mostraron que MAC, firstSeen/lastSeen, presencia y servicios permiten mantener continuidad aunque cambie la IP.", decision: "Construir una capa de identidad persistente y convertir el experimento en parte de WiFi Monitor.", result: "WiFi Monitor", projectHref: "/central/projects#wifi-monitor", icon: RadioTower },
  { name: "Acceso privado por dispositivo", status: "Validando", hypothesis: "Una herramienta sensible puede ser simple de usar sin quedar expuesta públicamente.", evidence: "Tailscale permite restringir transporte y WebAuthn/biometría puede elevar la verificación de acciones, pero la interfaz por sí sola no sustituye autorización de servidor.", decision: "Mantenerlo en Lab hasta definir un patrón común de autorización verificable para herramientas privadas BR.", result: null, projectHref: null, icon: ShieldCheck },
  { name: "Companion contextual", status: "Avanzó a Central", hypothesis: "Una guía contextual puede orientar mejor que un chatbot genérico si conserva intención y ubicación.", evidence: "Companion ya conserva el camino elegido durante la sesión y cambia su explicación entre Central, Lab y Projects.", decision: "Integrarlo como capa de navegación de BR Central y seguir ampliando su contexto conforme nazcan nuevas áreas.", result: "BR Central", projectHref: "/central", icon: Sparkles },
];

export default function LabPage() {
  return <main className="min-h-screen bg-[#09090b] text-[#f3eee6]">
    <div className="pointer-events-none fixed inset-x-0 top-0 h-[780px] bg-[radial-gradient(circle_at_16%_10%,rgba(57,189,248,0.12),transparent_30%),radial-gradient(circle_at_82%_12%,rgba(139,92,246,0.13),transparent_30%)]" />
    <header className="relative z-10 border-b border-white/[0.06] bg-[#09090b]/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/central" className="inline-flex items-center gap-2 text-sm font-black text-zinc-300 transition hover:text-white"><ArrowLeft className="h-4 w-4" /> BR Central</Link><span className="text-[10px] font-black uppercase tracking-[0.34em] text-cyan-300">BR Lab</span></div></header>

    <section className="relative z-10 mx-auto max-w-7xl px-5 pb-14 pt-16 sm:px-8 sm:pt-24"><div className="grid gap-10 lg:grid-cols-[1.2fr_.72fr] lg:items-start"><div><p className="text-[11px] font-black uppercase tracking-[0.32em] text-cyan-300">Antes de que algo sea proyecto //</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[0.94] tracking-[-0.06em] sm:text-7xl">Aquí todavía está permitido <span className="text-zinc-500">no saber.</span></h1><p className="mt-7 max-w-3xl text-base leading-8 text-zinc-400 sm:text-lg">BR Lab conserva la evidencia detrás de una decisión. No basta con que una idea suene bien: queremos saber qué probamos, qué aprendimos y por qué decidimos construir más —o detenernos.</p></div><BRCompanion /></div></section>

    <section className="relative z-10 mx-auto max-w-7xl px-5 pb-20 sm:px-8"><div className="mb-6 border-t border-white/[0.07] pt-7"><p className="text-[10px] font-black uppercase tracking-[0.3em] text-zinc-600">Registro de experimentos //</p><p className="mt-2 text-sm text-zinc-500">Hipótesis → evidencia → decisión → resultado.</p></div><div className="grid gap-4">
      {experiments.map(({ name,status,hypothesis,evidence,decision,result,projectHref,icon:Icon }, index) => <article key={name} className="rounded-[30px] border border-white/[0.075] bg-white/[0.025] p-6 sm:p-8"><div className="grid gap-8 lg:grid-cols-[.68fr_1.32fr]"><div><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl border border-cyan-300/15 bg-cyan-400/[0.05] text-cyan-200"><Icon className="h-5 w-5" /></span><span className="text-[10px] font-black uppercase tracking-[0.25em] text-zinc-600">EXP 0{index + 1}</span></div><h2 className="mt-6 text-3xl font-black tracking-[-0.04em]">{name}</h2><span className="mt-3 inline-flex items-center gap-2 rounded-full border border-cyan-300/15 px-3 py-1.5 text-xs font-black text-cyan-200">{result && <CheckCircle2 className="h-3.5 w-3.5" />}{status}</span><p className="mt-6 text-lg font-bold leading-8 text-zinc-200">{hypothesis}</p>{result && projectHref && <Link href={projectHref} className="mt-6 inline-flex items-center gap-2 text-sm font-black text-cyan-200 transition hover:text-white">Resultado: {result} <ArrowRight className="h-4 w-4" /></Link>}</div><div className="grid gap-3 sm:grid-cols-3"><LabCell label="Evidencia" text={evidence} /><LabCell label="Decisión" text={decision} /><LabCell label="Resultado" text={result ? `La prueba justificó avanzar a ${result}. El aprendizaje queda enlazado con lo que se construyó después.` : "Todavía no avanza. Falta evidencia suficiente para justificar convertir esta prueba en un sistema estable."} /></div></div></article>)}
    </div></section>

    <section className="relative z-10 mx-auto max-w-7xl px-5 pb-24 sm:px-8"><div className="rounded-[32px] border border-violet-300/15 bg-gradient-to-br from-cyan-500/[0.05] to-violet-500/[0.08] p-8 sm:p-10"><div className="flex items-center gap-3 text-cyan-200"><FlaskConical className="h-5 w-5" /><span className="text-[10px] font-black uppercase tracking-[0.3em]">Criterio de salida</span></div><h2 className="mt-5 max-w-4xl text-4xl font-black tracking-[-0.05em] sm:text-5xl">Avanzar también es una decisión que debe poder explicarse.</h2><p className="mt-5 max-w-3xl leading-7 text-zinc-400">Una prueba sale de Lab cuando el problema sigue siendo real, la evidencia cambia una decisión y existe una razón concreta para invertir en la siguiente etapa. Si no ocurre, el aprendizaje permanece aquí.</p><Link href="/central/projects" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#f3eee6] px-5 py-3 text-sm font-black text-[#09090b]">Seguir la evolución en Projects <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main>;
}

function LabCell({ label, text }: { label: string; text: string }) { return <div className="rounded-[22px] border border-white/[0.07] bg-black/15 p-5"><p className="text-[10px] font-black uppercase tracking-[0.24em] text-zinc-600">{label}</p><p className="mt-3 text-sm leading-6 text-zinc-400">{text}</p></div>; }
